In [401]:
import math
import numpy as np

In [402]:
# f = open("Input\data.txt", "r")
# print(f.read())
with open("Input\data.txt") as f:
    observations = [line.rstrip() for line in f]
    
print(observations)

['104.524317662043', '98.295390941985', '101.201300572309', '96.8258824775576', '99.7777844797209', '100.535882059444', '150.219247991425', '153.299171430611', '152.030452379689', '149.271446628265', '148.965391188617', '153.209523402459', '148.536116284592', '151.04160094104', '152.806933075742', '154.146132372137', '101.474895066967', '99.4181522342549', '99.7491679934576', '97.3801697598009', '150.700271545697', '146.088547777193', '152.142228905801', '104.346057541084', '152.941065491139', '147.6310565928', '147.400779027143', '145.465667366449', '152.762344617', '147.584883199481', '147.463428757649', '150.19276707899', '103.72260951414', '99.5057200177867', '154.25160489277', '148.616718935355', '149.20219245808', '152.519345863771', '145.867576505545', '153.743351614724', '103.925588352528', '99.9158517746542', '99.485572413414', '146.394671210885', '146.839092494125', '99.848607563626', '103.094508508026', '105.018453282783', '94.6266294243679', '100.410789870313', '100.7806323

In [403]:
for i, j in enumerate(observations):
    observations[i] = float(j)
    
print(observations)

[104.524317662043, 98.295390941985, 101.201300572309, 96.8258824775576, 99.7777844797209, 100.535882059444, 150.219247991425, 153.299171430611, 152.030452379689, 149.271446628265, 148.965391188617, 153.209523402459, 148.536116284592, 151.04160094104, 152.806933075742, 154.146132372137, 101.474895066967, 99.4181522342549, 99.7491679934576, 97.3801697598009, 150.700271545697, 146.088547777193, 152.142228905801, 104.346057541084, 152.941065491139, 147.6310565928, 147.400779027143, 145.465667366449, 152.762344617, 147.584883199481, 147.463428757649, 150.19276707899, 103.72260951414, 99.5057200177867, 154.25160489277, 148.616718935355, 149.20219245808, 152.519345863771, 145.867576505545, 153.743351614724, 103.925588352528, 99.9158517746542, 99.485572413414, 146.394671210885, 146.839092494125, 99.848607563626, 103.094508508026, 105.018453282783, 94.6266294243679, 100.410789870313, 100.780632342166, 98.3585134358939, 151.29390317797, 100.978651416809, 151.300787117846, 151.236439784471, 149.2

In [404]:
len(observations)

1000

In [405]:
with open("Input\parameters.txt") as f:
    lines = [line.rstrip() for line in f]
    
print(lines)

['2', '0.7\t0.3', '0.1\t0.9', '200\t100', '10\t10']


In [406]:
lines2 = []
mean = []
variance = []
tp = []

for i, j in enumerate(lines[0]):
    lines2.append(int(j))

tp.append(float(lines[1].split()[0]))
tp.append(float(lines[1].split()[1]))

tp.append(float(lines[2].split()[0]))
tp.append(float(lines[2].split()[1]))

mean.append(float(lines[3].split()[0]))
mean.append(float(lines[3].split()[1]))

variance.append(float(lines[4].split()[0]))
variance.append(float(lines[4].split()[1]))
    
# for i, j in enumerate(lines[1]):
#     lines2.append(j.split()[0])

# for i, j in enumerate(lines[2]):
#     lines2[i] = (j)
    
print(lines2, tp, mean, variance)

[2] [0.7, 0.3, 0.1, 0.9] [200.0, 100.0] [10.0, 10.0]


In [407]:
states = ()
for i in range(0, lines2[0]):
    states2 = (i + 1,)
    states = states + states2
    
print(states)
    

(1, 2)


In [408]:
transition_prob = {}
count = 0
for i in range (len(states)):
        transition_prob[i+1] = {}
        
for i in range (len(states)):
    for j in range (len(states)):
        count = count + 1
        transition_prob[i+1][j+1] = tp[count-1]

In [409]:
print(transition_prob)

{1: {1: 0.7, 2: 0.3}, 2: {1: 0.1, 2: 0.9}}


In [410]:
def calc_emission_prob(states, observations, mean, variance):
    emission_prob = {}

    for i in range (len(states)):
            emission_prob[i+1] = {}


    for i in range (len(states)):
        for j in range (len(observations)):

            emission_prob[i+1][j+1] = (1/((math. sqrt(variance[i]))* math. sqrt(2 * math.pi)))* math.exp(-((observations[j] - mean[i])**2)/(2*variance[i]))
            
    return emission_prob

In [411]:
emission_prob = calc_emission_prob(states, observations, mean, variance)
print(emission_prob)

{1: {1: 1.4389397118892748e-199, 2: 3.072909260631084e-226, 3: 1.3788410091660564e-213, 4: 8.90995562555163e-233, 5: 9.716885927631951e-220, 6: 1.8825196565625887e-216, 7: 1.9460185342686166e-55, 8: 5.518295484884097e-49, 9: 1.3603387071704856e-51, 10: 1.6616529525976536e-57, 11: 3.5013180643179405e-58, 12: 3.6291681627709474e-49, 13: 3.879565075058746e-59, 14: 1.1281023989469466e-53, 15: 5.472553267992457e-50, 16: 2.7798847481393666e-47, 17: 2.0503151884138996e-212, 18: 2.626545470346913e-221, 19: 7.293791295406557e-220, 20: 2.672093860699701e-230, 21: 2.1089762888140343e-54, 22: 9.733425855969697e-65, 23: 2.324014220059256e-51, 24: 2.6194179128635136e-200, 25: 1.0297052760547837e-49, 26: 3.533001926306316e-61, 27: 1.05501738489216e-61, 28: 3.322485902532002e-66, 29: 4.433632678947051e-50, 30: 2.7738496822333594e-61, 31: 1.4665221272596085e-61, 32: 1.705616233285995e-55, 33: 6.604471104514222e-203, 34: 6.334804891564642e-221, 35: 4.506341138052412e-47, 36: 5.872090824215731e-59, 37: 1

In [412]:
tp = np.array(tp).reshape(-1, 2)

print(tp)

[[0.7 0.3]
 [0.1 0.9]]


In [413]:


m1 = np.matmul(tp, tp)
while(1):
    m1 = np.matmul(m1, tp)
    a = np.isclose(m1, m1[0]).all()
    if(a == True):
        break
    
print(m1)

[[0.25000128 0.74999872]
 [0.24999957 0.75000043]]


In [414]:
stationary_prob = {}

for i in range(len(states)):
    stationary_prob[i+1] = round(m1[0][i], 3)
    
print(stationary_prob)

{1: 0.25, 2: 0.75}


In [415]:
def step_choose(v):
    hidden_states = []
    max_prob = - 10000000
    best_state = 0
    
    for item in v[-1]:
        if v[-1][item]["probability"] > max_prob:  #log nite hobeeeee, naile loop e dhukbe na
            max_prob = v[-1][item]["probability"]
            best_state = item
#             print("hello")
    hidden_states.append(best_state)
    previous = best_state

    
    for i in range(len(v) - 2, -1, -1):  #backtracking

        hidden_states.insert(0, v[i + 1][previous]["previous"])
        previous = v[i + 1][previous]["previous"]
        
    
    return hidden_states
    

In [416]:
def viterbi(obs, sts, sp, tp, ep):
    
    #vterbi forward part
    V = [{}]
    for i in sts:
        V[0][i] = {"probability": np.log(sp[i]) + np.log(ep[i][1]), "previous": 0}
   
    
    for t in range(1, len(obs)):
        V.append({})
            
    for t in range(1, len(obs)):
        
        for i in sts:
            max_tp = V[t - 1][sts[0]]["probability"] + np.log(tp[sts[0]][i])
            prev_st_selected = sts[0]
            for j in sts[1:]:
                tr_prob = V[t - 1][j]["probability"] + np.log(tp[j][i])
                if tr_prob > max_tp:
                    max_tp = tr_prob
                    prev_st_selected = j
                    

            max_prob = max_tp + np.log(ep[i][t+1])
            V[t][i] = {"probability": max_prob, "previous": prev_st_selected}
            
    
    options = step_choose(V)


    print ("The selected hidded states are " )
    print(options)
    
    
    count2 = 0
    count1 = 0
    output = ['0' for i in range(len(options))]
    
    for i in range (len(options)):
        if (options[i] == 2):
            count2 = count2 + 1
            output[i] ="\"La Nina\"\n"
        elif (options[i] == 1):
            count1 = count1 + 1
            output[i] = "\"El Nino\"\n"
    print(count1, count2)
    print(output)
    
    file1 = open('Output.txt', 'w')
    # Writing multiple strings
    # at a time
    file1.writelines(output)

    # Closing file
    file1.close()
    
            
#     print (" with highest probability of %s" % max_prob)



In [417]:
viterbi(observations,states,stationary_prob,transition_prob,emission_prob)

The selected hidded states are 
[2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2

# Baum-Welch

In [427]:
def forward(obs, sts, sp, tp, ep):
    
    #forward part
    V = [{}]
    
    s = 0.0
    for i in sts:
        V[0][i] = {"probability": sp[i] * ep[i][1]}
        s = s + V[0][i]["probability"]
    for i in sts:
        V[0][i]["probability"] = V[0][i]["probability"]/s
   
    
    for t in range(1, len(obs)):
        V.append({})
        
    summation = 0.0
    norm_sum = 0.0
    
            
    for t in range(1, len(obs)):
        
       
        for i in sts:
           
            for j in sts:
                tr_prob = V[t - 1][j]["probability"] * tp[j][i] * ep[i][t+1]
#                 print(tr_prob)
                summation  = summation  + tr_prob
#                 print(summation)
                
                    

#             max_prob = tr_prob  
            
            V[t][i] = {"probability": summation}
            norm_sum = norm_sum + V[t][i]["probability"]
            summation = 0.0
        
        for i in sts:
            V[t][i]["probability"] = V[t][i]["probability"]/norm_sum
            
        norm_sum = 0.0
        
            
            
            
            
    return V
            
    
   

In [428]:
def backward(obs, sts, sp, tp, ep):
    
    #forward part
    beta = [{}]
    last_index = len(obs)
    
    
   #     s = 0.0
    
    for t in range(1, len(obs)):
        beta.append({})
        
    for i in sts:
        beta[last_index-1][i] = {"probability": 1.0}
#         s = s + beta[last_index-1][i]["probability"]
        
#     for i in sts:
#         beta[last_index-1][i]["probability"] = beta[last_index-1][i]["probability"]/s
        
   
    
    
        
    summation = 0.0
    norm_sum = 0.0
            
    for t in range(len(obs)-2, -1, -1):
        
        
        for i in sts:
           
            for j in sts:
                tr_prob = beta[t + 1][j]["probability"] * tp[i][j]* ep[j][t+1]
#                 print(tr_prob)
                summation  = summation  + tr_prob
#                 print(summation)
                
                    

#             max_prob = tr_prob  
            
            beta[t][i] = {"probability": summation}
            norm_sum = norm_sum + beta[t][i]["probability"]
            summation = 0.0
            
        for i in sts:
            beta[t][i]["probability"] = beta[t][i]["probability"]/norm_sum
            
        norm_sum = 0.0
            
            
    return beta
            
    
   

In [429]:
def pi_star_calc(obs,sts,beta,alpha):
    pi_star = [{}]

    for t in range(1, len(obs)):
            pi_star.append({})


    norm_sum = 0.0

    for t in range(0, len(obs)):


        for i in sts:

            pi_star[t][i] = {'probability': alpha[t][i]["probability"] * beta[t][i]["probability"] }



            norm_sum = norm_sum + pi_star[t][i]["probability"]


        for i in sts:
            pi_star[t][i]["probability"] = pi_star[t][i]["probability"]/norm_sum

        norm_sum = 0.0
        
    return pi_star






In [430]:
def pi_star_star_calc(obs,sts,beta,alpha,tp,ep):
    
    pi_star_star = np.zeros((len(sts),len(sts),len(obs)-1))
    
#     for j in range(len(obs)-1):
#         for k in sts:
#             for l in sts:
#                 print(j, alpha[j][k]["probability"] , tp[k][l], ep[l][j+2], beta[j+1][l]["probability"])
#                 pi_star_star[k-1][l-1][j] = alpha[j][k]["probability"] * tp[k][l]*ep[l][j+2]*beta[j+1][l]["probability"]
#         s = np.sum(pi_star_star[:,:,j])
        
#         for k in sts:
#             for l in sts:
#                 pi_star_star[k-1][l-1][j] = pi_star_star[k-1][l-1][j]/s
                
                
        

    for t in range(1, len(obs)-1):
            pi_star_star.append({})
            
    for t in range (len(obs)-1):
        for i in sts:
            pi_star_star[t][i] = {}
            
    


    norm_sum = 0.0

    for t in range(0, len(obs)-1):


        for i in sts:
            
            for j in sts:
                pi_star_star[t][i][j] = {'probability': alpha[t][i]["probability"] * tp[i][j] * ep[j][t+1]* beta[t+1][j]["probability"]}
                

            



                norm_sum = norm_sum + pi_star_star[t][i][j]["probability"]


        for i in sts:
            for j in sts:
                pi_star_star[t][i][j]["probability"] = pi_star_star[t][i][j]["probability"]/norm_sum

        norm_sum = 0.0
        
    return pi_star_star






In [431]:
tp_got = tp.copy()
# print(tp_got)

mean_new = mean.copy()
var_new =  variance.copy()
print(mean_new)

while(1):
    
    emission_prob = calc_emission_prob(states, observations, mean_new, var_new)
    
    alpha = forward(observations, states, stationary_prob, transition_prob, emission_prob)
    beta = backward(observations, states, stationary_prob, transition_prob, emission_prob)
    pi_star = pi_star_calc(observations, states, beta, alpha)
    pi_star_star = pi_star_star_calc(observations, states, beta, alpha, transition_prob, emission_prob)

    tp_got_prev = tp_got.copy()

    sm = 0.0
    


    for i in states:
        for j in states:

            for t in range(len(pi_star_star)):
                sm = sm + pi_star_star[t][i][j]["probability"]

            tp_got[i-1][j-1] = sm
            sm = 0.0

    sm2 = 0.0        
    for i in states:
        for j in states:
            sm2 = sm2 + tp_got[i-1][j-1]
        for j in states:
            tp_got[i-1][j-1] = tp_got[i-1][j-1]/sm2

        sm2 = 0.0
        
    
    sm3 = 0.0
    sm4 = 0.0
    sm5 = 0.0
    sm6 = 0.0
    
    for k in states:
#         print(k)
        for t in range(len(observations)):
            sm3 = sm3 + pi_star[t][k]["probability"] * observations[t]
            sm4 = sm4 + pi_star[t][k]["probability"]
        mean_new[k-1] = sm3 / sm4
        sm3 = 0.0
        sm4 = 0.0
        print(mean_new[k-1])
        
    
    for k in states:
#         print(k)
        for t in range(len(observations)):
            sm5 = sm5 + pi_star[t][k]["probability"]* ((observations[t]-mean_new[k-1])**2)
            sm6 = sm6 + pi_star[t][k]["probability"]
        var_new[k-1] = (sm5 / sm6)
        sm5 = 0.0
        sm6 = 0.0
        
#     print(tp_got_prev, tp_got)
    comparison = tp_got_prev == tp_got
    equal_arrays = comparison.all()
    
    if equal_arrays == True:
        break
        
    




print(tp_got, mean_new, var_new)

[200.0, 100.0]
151.8926323722583
118.1823453718671
150.9090008155495
110.4727069431996
150.30655697679447
102.23499515057927
150.1899029184578
100.20979774082213
150.1898689024755
100.20940295792063
150.1898689024755
100.20940295792063
[[0.82795699 0.17204301]
 [0.21768707 0.78231293]] [150.1898689024755, 100.20940295792063] [5.031876996331308, 8.713465143646749]


In [432]:
m1 = np.matmul(tp_got, tp_got)
while(1):
    m1 = np.matmul(m1, tp_got)
    a = np.isclose(m1, m1[0]).all()
    if(a == True):
        break
    


stationary_prob2 = {}

for i in range(len(states)):
    stationary_prob2[i+1] = round(m1[0][i], 3)
    
print(stationary_prob2)

{1: 0.559, 2: 0.441}


In [433]:
file2 = open('parameters_learned.txt', 'w')
    # Writing multiple strings
    # at a time
    
for i in range(0,len(tp_got)):
    for j in range(0,len(tp_got[i])):
        file2.write(str(tp_got[i][j]))
        file2.write(" ")
    file2.write("\n")
file2.writelines(str(mean_new))
file2.write("\n")
file2.writelines(str(var_new))
file2.write("\n")


for j in range(0,len(m1[0])):
    
    file2.writelines(str(m1[0][j]))
    file2.write(" ")
    
file2.write("\n")



    # Closing file
file2.close()

In [434]:
emission_prob2 = calc_emission_prob(states, observations, mean_new, var_new)

tp_got2 = tp_got.flatten()
print(tp_got2)

[0.82795699 0.17204301 0.21768707 0.78231293]


In [435]:
transition_prob2 = {}
c = 0
for i in range (len(states)):
        transition_prob2[i+1] = {}
        
for i in range (len(states)):
    for j in range (len(states)):
        c = c + 1
        transition_prob2[i+1][j+1] = tp_got2[count-1]

In [399]:
viterbi(observations,states,stationary_prob2,transition_prob2,emission_prob2)

The selected hidded states are 
[2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2